### ISSUE TITLE
Nested array of objects

### ISSUE THREAD

**Issue by pasine** [Keyang/node-csvtojson#18]
I have a complex json structure to replicate. 
It is basically something like this: 

```
csv: [{
    levelA : {
    title: 'foo',
    levelB: [
      {
      title : 'bar',
      levelC: [
        {title : 'deep blue'},
        {title : 'deep red'},
        { ... }
        ]
      },
      { ... }
      ]
    }
  }, 
  { ... }
]
```

As you can see it is a deep nested structure with arrays of objects.
Do you think it would be possible to achieve this just using csvtojson parser keys or should I go for a custom parser?

**Comment by nandhu13** [comment]
Hi , my json(output) will have variable sized array of arrays.So i could not mention the index in csv file. For Example,[{ levelA: {title:'x',array1:[{content1:'aaa',content2:'xyz'},{content1:'ME',content2:'abc'}] } ,levelB: {title:'p',array1:[{content1:'uuu',content2:'ggg'}] }}]Could you please help me on this. In my json if the value is not present for a particular field, instead of null, that field should not be present

**Comment by Keyang** [comment]
Hi,
Could you give an example of what the csv looks like and what is the
expected JSON output?

~Keyang

**Comment by nandhu13** [comment]
Thanks for your immediate reply. my json output should be {title:mytitle,companyname:abc,department:[{deptid:1,section:sales,employee:[{name:aaa,age:29},{name:bbb,age:56,aliasname:myalias}]]},{title:title2,companyname:xyz,department:[{deprtid:2,section:marketing,employee:[{name:ccc,age:34,aliasname:alias2},{name:dd,age:55},{name:eee,age:27}]}]}...millions of records can be there like this..this is sample data and  not actual data.could you help me how to represent this json data in csv file and howto convert that CSV DATA TO JSON

**Comment by anandsrivastav1087** [comment]
marketoGUID,attributes
78351878,"{""Choice Number"":0,""Campaign Run ID"":19859,""Step ID"":40906,""Has Predictive"":true}"

i have this csv data, how to convert in json in node js. attributes containing list json object.
