### ISSUE TITLE
Poor performance parsing large CSVs using fromString

### ISSUE THREAD

**Issue by gabegorelick** [Keyang/node-csvtojson#251]
Parsing 100,000 row CSVs consistently takes ~80,000 ms, while parsing 10,000 rows takes ~40 ms using the same setup. With a streaming CSV parser, I would expect parse time to scale quasi-linearly with CSV size. I'm especially confused since large file performance is a touted feature of this library.

Here's my full test harness:
```js
const Papa = require('papaparse'); // could use anything to construct CSV
const csvtojson = require('csvtojson');

const data = [];
for (let i = 0; i < 100000; i++) {
    data.push({
        foo: Math.random()
    });
}

console.time('csvtojson');
return csvtojson()
    .fromString(Papa.unparse(data))
    .on('end', () => {
        console.timeEnd('csvtojson');
    });
```

I tested this on version 1.1.9.

**Comment by Keyang** [comment]
Interesting. as we never tested calling `fromString` with a large csv string as streaming is always preferable for large data. 
The fact is, if you store the generated csv data with 100000 rows as a file and call `fromFile` method instead, the time consumption increases linearly.
Here is my result using `fromFile`
```
10000 rows: 7.555ms
100000 rows: 80.312ms
```
The reason is because when large csv data passed to parser as a whole, there are too many lines which is firstly converted to a big Array and v8 will treat it as Hash Map instead of linear Array at C++ level which is extremely slow.
I will update the `fromString` implementation so that it creates a stream object internally. by doing so, we could use `highWaterMark` to control the amount of chunk be passed to the parser each time (which is by default 16kb), and this will gurantee v8 to use high performance linear array.

**Comment by gabegorelick** [comment]
I can confirm that switching to `fromFile` drops the parse time down to 400ms for 100k rows.

**Comment by gabegorelick** [comment]
I think I'm seeing the same slow performance with `fromStream` if the stream's chunks are too large. For example, if the underlying stream emits 100k rows in one chunk, performance gets really bad. It might make sense to internally break up large chunks, even if they're from a stream.

**Comment by Keyang** [comment]
Yea if you do 
```js
readable.push(largeString)
```
This will cause the same issue as node.js does not dictate the size being passed to downstream.
The `highWaterMark` is a signal but not enforced.
This problem is actually quite common in Node.JS stream.

The practice is to override the `_read(size)` method of readable:

```js
readable._read=function(size){
   readable.push(dataOfSize);
}
```
the `dataOfSize` should have equal or less length than `size` passed in

I will try to tackle this in parser. Thanks letting me know.

**Comment by Keyang** [comment]
refined `fromString` method by creating a readable stream internally in `v2.0.0`
