### ISSUE TITLE
It's keeping all processed lines on memory making useless for processing big files

### ISSUE THREAD

**Issue by rkmax** [Keyang/node-csvtojson#286]
I'm processing big files more than 800M, 3.7M lines and 10x bigger that

doing

```
import csv from 'csvtojson';
// ...
async processFunc(row) {
// ...
}
return csv(options)
    .fromFile(filepath)
    .subscribe(processFunc);
```

works fine but I'm noticing that internally the library is keeping for every parsed line, two things first the parsed line (raw string) and also some kind of object

by looking the code of the library I found (i dunno if it's the right place) that there's a Result.needEmitAll getter based on some calculations to see if it's false/true.

**Could you please explain how i can force this to be false**

![imagen](https://user-images.githubusercontent.com/395707/47236900-16c5ec80-d3a3-11e8-92e2-78b0e4663f91.png)

When I force false (by changing the source code on node_modules) by the same iterations the change is notable

![imagen](https://user-images.githubusercontent.com/395707/47237559-1a5a7300-d3a5-11e8-9eba-0068bbb73bca.png)

**Comment by rkmax** [comment]
In my case I need call .then because I need to wait for the file been processed to do more things. maybe will be great pass this as an option  `csv({needEmitAll: false}) `

**Comment by Keyang** [comment]
added parameter "needEmitAll"

**Comment by avimar** [comment]
Thanks, I think I may have ran into this same issue.

**Comment by stevenmasci** [comment]
Hi all, thanks for documenting this issue.

I'm having a related memory problem, not sure if it's due to the library or how I've structured my code, but I'm hoping someone might be able to point me in the right direction. 

I require the complete JSON result to be built as I need need to do further processing afterwards, so this means depending on the csv file I could be consuming a lot of memory.

```js
const content = await csv().fromString(csvString)
```

The problem I'm having is when the function finishes executing the garbage collector does not seem to be collecting the array of json objects once the function finishes or goes out of scope, which is what I'd expect to happen (eventually). Even forcing a collection with global.gc(); doesn't work.

Is there a possibility something in the csvtojson library is maintaining references to elements in the JSON array preventing collection?
