### ISSUE TITLE
Stream mode does not produce an array of JSON

### ISSUE THREAD

**Issue by mcqj** [Keyang/node-csvtojson#321]
I am not sure what the expected behaviour is.
My output is one JSON object per line with no wrapping array and no comma separators e.g.

{name:"Joe Bloggs",status:"alive"}
{name:"Alice Kay",status:"deceased"}

etc.

**Comment by GioLogist** [comment]
+1 on this

**Comment by ushakov-ruslan** [comment]
The same here. It's a huge problem.

**Comment by Keyang** [comment]
Duplicate of #307 
Will be covered by 2.0.9

**Comment by adams-family** [comment]
Hi, I think that this ticket should not be closed because the array generated is syntactically incorrect, since it contains a comma after the last row:

Received result:
[
  { "Name": "Peter" },
  { "Name": "Anna" },
  { "Name": "Jean" },
]
Expected result:
[
  { "Name": "Peter" },
  { "Name": "Anna" },
  { "Name": "Jean" }
]

Using v 2.0.10.

**Comment by cdimascio** [comment]
@adams-family the following issue exists for the trailing comma issue, https://github.com/Keyang/node-csvtojson/issues/333
