### ISSUE TITLE
Conversion fails with CRLF

### ISSUE THREAD

**Issue by Izhaki** [Keyang/node-csvtojson#35]
The following file:

    
    Date, Type, Description, Value, Balance, Account Name, Account Number
    
    11/04/2012,DPC,"'CALL REF.NO. 1778 , FROM A/C 12345678",50.00,149.47,"'Some Business Ltd","'123456-24438749",

Reasons:
* The first line endings are CRLF (\r\n)
* The CSV starts with a blank line (removing the first line solves the issue).

**Comment by Keyang** [comment]
That's interesting.
I will take a look soon.

~Keyang

**Comment by larsmoil** [comment]
I noticed the same thing. I think the issue arises when the CSV has different line endings than the OS your computer is running. For me the CSV file has CRLF line endings, but I was running the conversion on a Mac.

I think it's because of this line: https://github.com/Keyang/node-csvtojson/blob/master/libs/core/CSVLine.js#L11 (`var eol = os.EOL;`)

That initialisation can probably be removed, as line ending format is detected from the content further down in the same file? https://github.com/Keyang/node-csvtojson/blob/master/libs/core/CSVLine.js#L42-L48

**Comment by gCurtisCT** [comment]
This may be related to #55 ?

**Comment by Keyang** [comment]
I think it is related to #53 which is fixed in 0.4.2

**Comment by Keyang** [comment]
Close with #55
