### ISSUE TITLE
How do i create an array of objects?

### ISSUE THREAD

**Issue by mohan2020** [Keyang/node-csvtojson#4]
i.e. something like this 

"addresses":[ 
 {"type":"work", "address_line1":"val1", "address_line2":"val2"},
 {"type"home","address_line1":"val3", "address_line2":"val4" }
 ]

Is that possible now? or does it require a custom parser to be written?

Thanks! Seems like a promising solution.

**Comment by MartinConde** [comment]
I am having a similar issue so thought to re-open this one instead of a new one..

My csv is as follows:

slug,name,image,price,gallery
bloom,bloom,placeholder.png,14.95,image,image

I would like to make an array out of gallery, so that I have the various images as objects to later iterate over them. No matter what kind of brackets etc I use, I can't get it to work, any input would be much appreciated :)
