### ISSUE TITLE
Add new feature to convert CSV to JSON where first row in csv is not a column name 

### ISSUE THREAD

**Issue by gauravgupta90** [Keyang/node-csvtojson#48]
You can see Demo here: http://www.convertcsv.com/csv-to-json.htm

This is an input data read from CSV :

productId,classification_id,mfgDate,gross_price,retail_price,color,size
CC102-PDMI-001,eClass_5.1.3,10/3/2014,12,40,green,40
CC200-009-001,eClass_5.1.3,11/3/2014,5,3,blue,38
CC200-070-001,eClass_5.1.3,10/4/2014,15,13,red,45
CC200-099,eClass_5.1.3,10/5/2014,20,17,orange,28
CC200-100,eClass_5.1.3,10/3/2014,5,4,black,32

And expected resulted JSON: 
[
  {
    "FIELD1":"productId",
    "FIELD2":"classification_id",
    "FIELD3":"mfgDate",
    "FIELD4":"gross_price",
    "FIELD5":"retail_price",
    "FIELD6":"color",
    "FIELD7":"size"
  },
  {
    "FIELD1":"CC102-PDMI-001",
    "FIELD2":"eClass_5.1.3",
    "FIELD3":"10/3/2014",
    "FIELD4":"12",
    "FIELD5":"40",
    "FIELD6":"green",
    "FIELD7":"40"
  },
  {
    "FIELD1":"CC200-009-001",
    "FIELD2":"eClass_5.1.3",
    "FIELD3":"11/3/2014",
    "FIELD4":"5",
    "FIELD5":"3",
    "FIELD6":"blue",
    "FIELD7":"38"
  },
  {
    "FIELD1":"CC200-070-001",
    "FIELD2":"eClass_5.1.3",
    "FIELD3":"10/4/2014",
    "FIELD4":"15",
    "FIELD5":"13",
    "FIELD6":"red",
    "FIELD7":"45"
  },
  {
    "FIELD1":"CC200-099",
    "FIELD2":"eClass_5.1.3",
    "FIELD3":"10/5/2014",
    "FIELD4":"20",
    "FIELD5":"17",
    "FIELD6":"orange",
    "FIELD7":"28"
  },
  {
    "FIELD1":"CC200-100",
    "FIELD2":"eClass_5.1.3",
    "FIELD3":"10/3/2014",
    "FIELD4":"5",
    "FIELD5":"4",
    "FIELD6":"black",
    "FIELD7":"32"
  }
]

**Comment by dtsn** [comment]
+1

**Comment by fontanon** [comment]
Yes please!

Also, passing a header line to Converter as a parameter for CSV files with no header row would be awsome. May I open an enhacement issue for that?

**Comment by KrishnaPG** [comment]
Wondering if this has been implemented.

Ability to specify whether the data contains header or not would be a very valuable feature.

Also, being able to specify manual headers (column names) is a very good option. 
*    if the data does not contain header row, then the supplied manual names can be used 
*    if the data already contains header row, then manually supplied names should take precedence over the ones in the header

In fact, if column names can be supplied as key-value pairs (such as name:type) then the supplied type can also be used for auto conversion of the field. For example,
````
symb, dt, oprice, cprice, qty
MSFT,17-AUG-2015,  23.5,  25.3, 123
UNKN,17-AUG-2015,  "-"  ,  "-",  "-"
````
then for parsing
````
new CSV2Json({ constructResult: false, trim: true, checkType: true, 
columns:{
   symbol: string,
   date: Date,
   openPrice: float,
   closePrice: float,
   quantity: float
}});
}
````
should map the supplied column names and type in that order and produce something like
````
{
   symbol: 'MSFT',
   date: Date('17-Aug-2015'),
   openPrice: 23.50,
   closePrice: 25.30,
   quantity: 123  
}
{
   symbol: 'UNKN',
   date: Date('17-Aug-2015'),
   openPrice: 0,
   closePrice: 0,
   quantity: 0
}
````
The problem is, right now the system does not convert the "-" entries in the second row to floats (since it does not know the column type), and we have to manually post-process all the data again.
